apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-analytics-api
  labels:
    app: netflix-analytics-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-analytics-api
  template:
    metadata:
      labels:
        app: netflix-analytics-api
    spec:
      containers:
      - name: api
        image: ghcr.io/yourusername/netflix-behavior-pipeline:latest
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: SNOWFLAKE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: snowflake-secret
              key: account
        - name: SNOWFLAKE_USER
          valueFrom:
            secretKeyRef:
              name: snowflake-secret
              key: user
        - name: SNOWFLAKE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snowflake-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-analytics-api-service
spec:
  selector:
    app: netflix-analytics-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-dashboard
  labels:
    app: netflix-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-dashboard
  template:
    metadata:
      labels:
        app: netflix-dashboard
    spec:
      containers:
      - name: dashboard
        image: ghcr.io/yourusername/netflix-behavior-pipeline:latest
        command: ["streamlit"]
        args: ["run", "src/dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
        ports:
        - containerPort: 8501
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-dashboard-service
spec:
  selector:
    app: netflix-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer 